src/Entity/Link.php
<?php

namespace App\Entity;

use App\Repository\LinkRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=LinkRepository::class)
 */
class Link
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Le nom ne peut être vide !")
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Le lien ne peut être vide !")
     */
    private $link;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $IsActivated;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="links")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=VisitLink::class, mappedBy="link")
     */
    private $visitLinks;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"id", "CreatedAt", "name"})
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logo;

    /**
     * @ORM\Column(type="boolean")
     */
    private $iconIsActivated;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isArchived;

    /**
     * @ORM\Column(type="integer")
     */
    private $scale;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishFrom;

    public function __construct()
    {
        $this->visitLinks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getIsActivated(): ?bool
    {
        return $this->IsActivated;
    }

    public function setIsActivated(bool $IsActivated): self
    {
        $this->IsActivated = $IsActivated;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|VisitLink[]
     */
    public function getVisitLinks(): Collection
    {
        return $this->visitLinks;
    }

    public function addVisitLink(VisitLink $visitLink): self
    {
        if (!$this->visitLinks->contains($visitLink)) {
            $this->visitLinks[] = $visitLink;
            $visitLink->setLink($this);
        }

        return $this;
    }

    public function removeVisitLink(VisitLink $visitLink): self
    {
        if ($this->visitLinks->contains($visitLink)) {
            $this->visitLinks->removeElement($visitLink);
            // set the owning side to null (unless already changed)
            if ($visitLink->getLink() === $this) {
                $visitLink->setLink(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getIconIsActivated(): ?bool
    {
        return $this->iconIsActivated;
    }

    public function setIconIsActivated(bool $iconIsActivated): self
    {
        $this->iconIsActivated = $iconIsActivated;

        return $this;
    }

    public function getIsArchived(): ?bool
    {
        return $this->isArchived;
    }

    public function setIsArchived(bool $isArchived): self
    {
        $this->isArchived = $isArchived;

        return $this;
    }

    public function getScale(): ?int
    {
        return $this->scale;
    }

    public function setScale(int $scale): self
    {
        $this->scale = $scale;

        return $this;
    }

    public function getPublishFrom(): ?\DateTimeInterface
    {
        return $this->publishFrom;
    }

    public function setPublishFrom(?\DateTimeInterface $publishFrom): self
    {
        $this->publishFrom = $publishFrom;

        return $this;
    }

    public function __toString()
    {
        return $this->link;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="L'email ne peut être vide !")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Link::class, mappedBy="user")
     */
    private $links;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le pseudo ne peut être vide !")
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"pseudo"})
     */
    private $slug;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $color;

    /**
     * @ORM\OneToOne(targetEntity=UserAvatar::class, cascade={"persist", "remove"})
     */
    private $avatar;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageName;

    /**
     * @ORM\OneToMany(targetEntity=Newsletter::class, mappedBy="user")
     */
    private $newsletter;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $newsletterIsActived;

    public function __construct()
    {
        $this->links = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Link[]
     */
    public function getLinks(): Collection
    {
        return $this->links;
    }

    public function addLink(Link $link): self
    {
        if (!$this->links->contains($link)) {
            $this->links[] = $link;
            $link->setUser($this);
        }

        return $this;
    }

    public function removeLink(Link $link): self
    {
        if ($this->links->contains($link)) {
            $this->links->removeElement($link);
            // set the owning side to null (unless already changed)
            if ($link->getUser() === $this) {
                $link->setUser(null);
            }
        }

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(?string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getAvatar(): ?UserAvatar
    {
        return $this->avatar;
    }

    public function setAvatar(?UserAvatar $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function __toString()
    {
        return $this->email;
    }

    public function getNewsletter(): ?Newsletter
    {
        return $this->newsletter;
    }

    public function setNewsletter(?Newsletter $newsletter): self
    {
        $this->newsletter = $newsletter;

        // set (or unset) the owning side of the relation if necessary
        $newUser = null === $newsletter ? null : $this;
        if ($newsletter->getUser() !== $newUser) {
            $newsletter->setUser($newUser);
        }

        return $this;
    }

    public function getNewsletterIsActived(): ?bool
    {
        return $this->newsletterIsActived;
    }

    public function setNewsletterIsActived(?bool $newsletterIsActived): self
    {
        $this->newsletterIsActived = $newsletterIsActived;

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\UserAvatar;
use App\Form\AvatarType;
use App\Form\CustomizationFormType;
use App\Repository\LinkRepository;
use App\Repository\NewsletterRepository;
use App\Service\UserService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class UserController extends AbstractController
{
    /**
     * @Route("/myprofile", name="user_profil")
     */
    public function index(LinkRepository $linkRepository)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $user = $this->getUser();

        $links = $linkRepository->findByUserAndIsNotAchived($user);

        return $this->render('user/index.html.twig', [
            'links' => $links,
        ]);
    }

    /**
     * @Route("/myprofile/customization", name="user_customization")
     */
    public function customization(Request $request, UserService $userService, TranslatorInterface $translator)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $user = $this->getUser();

        $form = $this->createForm(CustomizationFormType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $form->getData();
    
            $userService->edit($user);

            $this->addFlash('success', $translator->trans('Your modification is saved'));
            
            return $this->redirectToRoute('user_profil');
        }

        return $this->render('user/customization.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/myprofile/avatar", name="user_avatar")
     */
    public function avatar(Request $request, UserService $userService, TranslatorInterface $translator)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $userAvatar = new UserAvatar();

        $form = $this->createForm(AvatarType::class, $userAvatar);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userAvatar = $form->getData();
    
            $avatar = $userService->addAvatar($userAvatar);
            $userService->setAvatar($avatar, $this->getUser());

            $this->addFlash('success', $translator->trans('Your avatar is added'));
            
            return $this->redirectToRoute('user_profil');
        }

        return $this->render('user/avatar.html.twig', [
            'form' => $form->createView(),
            'user' => $this->getUser(),
        ]);
    }

    /**
     * @Route("/myprofile/newsletter", name="user_newsletter")
     */
    public function newsletter(NewsletterRepository $newsletterRepository)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $newsletters = $newsletterRepository->findByUser($this->getUser());
        
        return $this->render('user/newsletter.html.twig', [
            'newsletters' => $newsletters,
        ]);
    }

    /**
     * @Route("/myprofile/newsletter/export", name="user_newsletter_export")
     */
    public function newsletterExport(NewsletterRepository $newsletterRepository)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $myVariableCSV = "Email;\n";
      
        $members = $newsletterRepository->findByUser($this->getUser());

        foreach ($members as $member) {
            $myVariableCSV .= $member->getEmail() . ";\n";
        }

        return new Response(
            $myVariableCSV,
            200,
            [
                 'Content-Type' => 'application/vnd.ms-excel',
                 "Content-disposition" => "attachment; filename=export_newsletter.csv"
              ]
        );
    }
}

templates/user/avatar.html.twig
{% extends 'base.html.twig' %}

{% block title %}WoolTree | {{ app.user.pseudo }}{% endblock %}

{% block body %}

{% for message in app.flashes('success') %}
    <div class="alert alert-success alert-dismissible fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}
{% for message in app.flashes('danger') %}
    <div class="alert alert-danger alert-dismissible fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}

<h3>{% trans %}Customization{% endtrans %}</h3>

<div class="article-container my-1">
    {% set avatar = '/uploads/avatar/' ~ user.imageName %}

    {% if user.imageName %}
        <div>
            <img class="img-fluid rounded-circle" src="{{ asset(avatar)| imagine_filter('squared_thumbnail_small') }}">
        </div>
    {% endif %}
   
</div>

 {{ form_start(form) }}
        {{ form_row(form.imageFile, {'attr': {'class': 'form-control'}}) }}
        <p></p>
        <button type="submit" class="btn btn-outline-secondary">{% trans %}Save{% endtrans %}</button>
    {{ form_end(form) }}

{% endblock %}

templates/user/customization.html.twig
{% extends 'base.html.twig' %}

{% block title %}WoolTree | {{ app.user.pseudo }}{% endblock %}

{% block body %}

{% for message in app.flashes('success') %}
    <div class="alert alert-success alert-dismissible fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}
{% for message in app.flashes('danger') %}
    <div class="alert alert-danger alert-dismissible fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}

<h3>{% trans %}Customization{% endtrans %}</h3>

 {{ form_start(form) }}
        {{ form_row(form.pseudo, {'attr': {'class': 'form-control'}}) }}
        {{ form_row(form.newsletterIsActived, {'attr': {'class': 'form-control'}}) }}
        {{ form_row(form.color, {'attr': {'class': 'form-control'}}) }}
        <p></p>
        <button type="submit" class="btn btn-outline-secondary">{% trans %}Save{% endtrans %}</button>
    {{ form_end(form) }}

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}WoolTree | {{ app.user.pseudo }}{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

{% for message in app.flashes('success') %}
    <div class="alert alert-success alert-dismissible fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}
{% for message in app.flashes('danger') %}
    <div class="alert alert-danger alert-dismissible fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}

<h3>{% trans %}Your links dashboard{% endtrans %}</h3>

<nav class="navbar navbar-expand navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{{ path('link_create') }}"><i class="fas fa-plus-circle"></i> {% trans %}Add new link{% endtrans %}</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-cog"></i> {% trans %}Customization{% endtrans %}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{{ path('user_customization') }}">{% trans %}My options{% endtrans %}</a>
          <a class="dropdown-item" href="{{ path('user_avatar') }}">{% trans %}Avatar{% endtrans %}</a>
          {% if app.user.newsletterIsActived %}
            <a class="dropdown-item" href="{{ path('user_newsletter') }}">{% trans %}Newletter Members{% endtrans %}</a>
          {% endif %}
        </div>
      </li>
    </ul>
  </div>
</nav>

<table class="table">
  <thead>
    <tr>
      <th scope="col">URL</th>
    </tr>
  </thead>
  <tbody>
    {% for link in links %}
        <tr>
            <td class="align-middle">
              <p><strong>{{ link.name }}</strong></p>
              <button type="button" class="btn btn-outline-success">
                <a href="{{ path('link_edit', {'slug': link.slug}) }}"><i class="fas fa-edit"></i></a>
              </button>
              {% if link.isActivated %}
                <button type="button" class="btn btn-outline-secondary">
                  <a href="{{ path('link_visibility', {'slug': link.slug}) }}"><i class="fas fa-eye"></i></a>
                </button>
              {% else %}
                  <button type="button" class="btn btn-outline-secondary">
                    <a href="{{ path('link_visibility', {'slug': link.slug}) }}"><i class="fas fa-eye-slash"></i></a>
                  </button>
              {% endif %}
              <button type="button" class="btn btn-outline-info">
                <a href="{{ path('link_up', {'slug': link.slug}) }}"><i class="fas fa-plus-square"></i></a>
              </button>
              <button type="button" class="btn btn-info">
                <span class="badge badge-light">{{ link.scale }}</span>
              </button>
              <button type="button" class="btn btn-outline-info">
                <a href="{{ path('link_down', {'slug': link.slug}) }}"><i class="fas fa-minus-square"></i></a>
              </button>
              <button type="button" class="btn btn-outline-secondary">
                <a href="{{ path('link_stats', {'slug': link.slug}) }}"><i class="fas fa-chart-line"></i> <span class="badge badge-secondary">{{ link.visitLinks|length}}</span></a>
              </button>
              <button type="button" class="btn btn-outline-danger">
                <a href="{{ path('link_delete', {'slug': link.slug}) }}"><i class="fas fa-trash-alt"></i></a>
              </button>
            </td>
        </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}

templates/user/newsletter.html.twig
{% extends 'base.html.twig' %}

{% block title %}WoolTree | {{ app.user.pseudo }}{% endblock %}

{% block body %}

{% for message in app.flashes('success') %}
    <div class="alert alert-success alert-dismissible fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}
{% for message in app.flashes('danger') %}
    <div class="alert alert-danger alert-dismissible fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}

<h3>{% trans %}Newsletter Members{% endtrans %}</h3>

<a href="{{ path('user_newsletter_export') }}" class="btn btn-outline-secondary" role="button" aria-disabled="true">{% trans %}Export to CSV{% endtrans %}</a>

<div class="article-container my-1">
    <table class="table">
        <thead>
            <tr>
            <td><strong>{% trans %}Newsletter Members{% endtrans %}</strong></th>
            </tr>
        </thead>
        <tbody>
            {% for newsletter in newsletters %}
                <tr>
                    <td>{{ newsletter.email }}</th>
                </tr>
            {% endfor %}
        </tbody>
    </table>  
</div>

{% endblock %}